package ao.creativemode.kixi.feed.dto.post;

import java.time.LocalDateTime;

public record PostResponse(
        Long id,
        Long authorAccountId,
        Long schoolYearId,
        Long courseId,
        Long classId,
        String type,
        String title,
        String content,
        Boolean isAutoGenerated,
        Long commentCount,
        Boolean hasReacted,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {}