package ao.creativemode.kixi.feed.service;

import ao.creativemode.kixi.identity.repository.AccountRepository;
import ao.creativemode.kixi.shared.exception.ApiException;
import ao.creativemode.kixi.feed.dto.post.*;
import ao.creativemode.kixi.feed.dto.postComment.PostCommentRequest;
import ao.creativemode.kixi.feed.dto.postComment.PostCommentResponse;
import ao.creativemode.kixi.feed.dto.postReaction.PostReactionRequest;
import ao.creativemode.kixi.feed.dto.postReport.PostReportRequest;
import ao.creativemode.kixi.feed.dto.postReport.PostReportResponse;
import ao.creativemode.kixi.feed.model.Post;
import ao.creativemode.kixi.feed.model.PostComment;
import ao.creativemode.kixi.feed.model.PostReaction;
import ao.creativemode.kixi.feed.model.PostReport;
import ao.creativemode.kixi.feed.repository.PostCommentRepository;
import ao.creativemode.kixi.feed.repository.PostReactionRepository;
import ao.creativemode.kixi.feed.repository.PostReportRepository;
import ao.creativemode.kixi.feed.repository.PostRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;

@Service
public class PostService {

    private static final int AUTO_HIDE_REPORT_THRESHOLD = 5;

    private final PostRepository postRepository;
    private final PostReactionRepository reactionRepository;
    private final PostCommentRepository commentRepository;
    private final PostReportRepository reportRepository;
    private final AccountRepository accountRepository;

    public PostService(PostRepository postRepository,
                       PostReactionRepository reactionRepository,
                       PostCommentRepository commentRepository,
                       PostReportRepository reportRepository,
                       AccountRepository accountRepository) {
        this.postRepository = postRepository;
        this.reactionRepository = reactionRepository;
        this.commentRepository = commentRepository;
        this.reportRepository = reportRepository;
        this.accountRepository = accountRepository;
    }

    public Flux<PostResponse> getFeed(Long accountId, Long schoolYearId, Long courseId, Long classId, int page, int limit) {
        long offset = (long) Math.max(0, page - 1) * limit;

        return postRepository.findFeedPosts(schoolYearId, courseId, classId, offset, limit)
                .flatMap(post -> mapToResponse(post, accountId));
    }

    public Mono<Long> getFeedTotalCount(Long schoolYearId, Long courseId, Long classId) {
        return postRepository.countFeedPosts(schoolYearId, courseId, classId);
    }

    @Transactional
    public Mono<PostResponse> createPost(Long accountId, Long schoolYearId, Long courseId, Long classId, PostRequest request) {
        return accountRepository.findByIdAndDeletedAtIsNull(accountId)
                .switchIfEmpty(Mono.error(ApiException.notFound("Account not found")))
                .flatMap(account -> {
                    Post post = new Post();
                    post.setAuthorAccountId(accountId);
                    post.setSchoolYearId(schoolYearId);
                    post.setCourseId(courseId);
                    post.setClassId(classId);
                    post.setType(request.type().getValue());
                    post.setTitle(request.title() != null ? request.title().trim() : null);
                    post.setContent(request.content().trim());
                    post.setIsAutoGenerated(false);
                    post.setIsHidden(false);
                    post.setCreatedAt(LocalDateTime.now());
                    post.setUpdatedAt(LocalDateTime.now());

                    return postRepository.save(post);
                })
                .flatMap(saved -> mapToResponse(saved, accountId))
                .onErrorMap(DataIntegrityViolationException.class,
                        e -> ApiException.badRequest("Invalid post request payload or scope parameters"));
    }

    @Transactional
    public Mono<Void> toggleReaction(Long postId, Long accountId, PostReactionRequest request) {
        String type = request.reaction().getValue();

        return postRepository.findByIdAndIsHiddenFalseAndDeletedAtIsNull(postId)
                .switchIfEmpty(Mono.error(ApiException.notFound("Post not found")))
                .flatMap(post -> reactionRepository.findByPostIdAndAccountIdAndType(postId, accountId, type)
                        .flatMap(existing -> reactionRepository.deleteByPostIdAndAccountIdAndType(postId, accountId, type))
                        .switchIfEmpty(Mono.defer(() -> {
                            PostReaction reaction = new PostReaction();
                            reaction.setPostId(postId);
                            reaction.setAccountId(accountId);
                            reaction.setType(type);
                            reaction.setCreatedAt(LocalDateTime.now());
                            return reactionRepository.save(reaction).then();
                        })));
    }

    @Transactional
    public Mono<PostCommentResponse> addComment(Long postId, Long accountId, PostCommentRequest request) {
        return postRepository.findByIdAndIsHiddenFalseAndDeletedAtIsNull(postId)
                .switchIfEmpty(Mono.error(ApiException.notFound("Post not found")))
                .flatMap(post -> {
                    PostComment comment = new PostComment();
                    comment.setPostId(postId);
                    comment.setAuthorAccountId(accountId);
                    comment.setContent(request.content().trim());
                    comment.setIsHidden(false);
                    comment.setCreatedAt(LocalDateTime.now());
                    comment.setUpdatedAt(LocalDateTime.now());

                    return commentRepository.save(comment);
                })
                .map(saved -> new PostCommentResponse(
                        saved.getId(),
                        saved.getPostId(),
                        saved.getAuthorAccountId(),
                        saved.getContent(),
                        saved.getIsHidden(),
                        saved.getCreatedAt(),
                        saved.getUpdatedAt()
                ));
    }

    @Transactional
    public Mono<PostReportResponse> reportPost(Long postId, Long reporterAccountId, PostReportRequest request) {
        return postRepository.findByIdAndIsHiddenFalseAndDeletedAtIsNull(postId)
                .switchIfEmpty(Mono.error(ApiException.notFound("Post not found")))
                .flatMap(post -> reportRepository.existsByPostIdAndReporterAccountId(postId, reporterAccountId))
                .flatMap(alreadyReported -> {
                    if (Boolean.TRUE.equals(alreadyReported)) {
                        return Mono.error(ApiException.conflict("You have already reported this post"));
                    }

                    PostReport report = new PostReport();
                    report.setPostId(postId);
                    report.setReporterAccountId(reporterAccountId);
                    report.setReason(request.reason().trim());
                    report.setCreatedAt(LocalDateTime.now());

                    return reportRepository.save(report);
                })
                .flatMap(savedReport -> reportRepository.countByPostId(postId)
                        .flatMap(count -> {
                            if (count >= AUTO_HIDE_REPORT_THRESHOLD) {
                                return hidePost(postId).thenReturn(savedReport);
                            }
                            return Mono.just(savedReport);
                        }))
                .map(saved -> new PostReportResponse(
                        saved.getId(),
                        saved.getPostId(),
                        saved.getReporterAccountId(),
                        saved.getReason(),
                        saved.getCreatedAt()
                ));
    }

    @Transactional
    public Mono<Void> hidePost(Long postId) {
        return postRepository.findById(postId)
                .switchIfEmpty(Mono.error(ApiException.notFound("Post not found")))
                .flatMap(post -> {
                    post.setIsHidden(true);
                    post.setUpdatedAt(LocalDateTime.now());
                    return postRepository.save(post);
                })
                .then();
    }

    private Mono<PostResponse> mapToResponse(Post post, Long currentAccountId) {
        Mono<Long> commentCountMono = commentRepository.countByPostIdAndIsHiddenFalseAndDeletedAtIsNull(post.getId());
        Mono<Boolean> hasReactedMono = reactionRepository.existsByPostIdAndAccountId(post.getId(), currentAccountId);

        return Mono.zip(commentCountMono, hasReactedMono)
                .map(tuple -> new PostResponse(
                        post.getId(),
                        post.getAuthorAccountId(),
                        post.getSchoolYearId(),
                        post.getCourseId(),
                        post.getClassId(),
                        post.getType(),
                        post.getTitle(),
                        post.getContent(),
                        post.getIsAutoGenerated(),
                        tuple.getT1(), // commentCount
                        tuple.getT2(), // hasReacted
                        post.getCreatedAt(),
                        post.getUpdatedAt()
                ));
    }
}