package ao.creativemode.kixi.feed.service;

import ao.creativemode.kixi.feed.dto.post.PostRequest;
import ao.creativemode.kixi.feed.dto.post.PostResponse;
import ao.creativemode.kixi.feed.enums.PostType;
import ao.creativemode.kixi.feed.model.Post;
import ao.creativemode.kixi.feed.model.PostReport;
import ao.creativemode.kixi.feed.repository.PostCommentRepository;
import ao.creativemode.kixi.feed.repository.PostReactionRepository;
import ao.creativemode.kixi.feed.repository.PostReportRepository;
import ao.creativemode.kixi.feed.repository.PostRepository;
import ao.creativemode.kixi.identity.model.Account;
import ao.creativemode.kixi.identity.repository.AccountRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.time.LocalDateTime;
import java.util.Optional;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PostServiceTest {

    @Mock
    private PostRepository postRepository;

    @Mock
    private PostReactionRepository reactionRepository;

    @Mock
    private PostCommentRepository commentRepository;

    @Mock
    private PostReportRepository reportRepository;

    @Mock
    private AccountRepository accountRepository;

    @InjectMocks
    private PostService postService;

    private Account mockAccount;
    private Post mockPost;

    @BeforeEach
    void setUp() {
        mockAccount = new Account();
        mockAccount.setId(1L);
        mockAccount.setEmail("student@itel.ao");

        mockPost = new Post();
        mockPost.setId(100L);
        mockPost.setAuthorAccountId(1L);
        mockPost.setContent("Sample test post content");
        mockPost.setType(PostType.TOPIC.getValue());
        mockPost.setIsHidden(false);
        mockPost.setIsAutoGenerated(false);
        mockPost.setCreatedAt(LocalDateTime.now());
        mockPost.setUpdatedAt(LocalDateTime.now());
    }

    @Test
    void createPost_ShouldSucceed_WhenAccountExists() {
        // Arrange
        PostRequest request = new PostRequest(PostType.TOPIC, "Test Title", "Sample test post content");

        when(accountRepository.findByIdAndDeletedAtIsNull(1L)).thenReturn(Mono.just(mockAccount));
        when(postRepository.save(any(Post.class))).thenReturn(Mono.just(mockPost));
        when(commentRepository.countByPostIdAndIsHiddenFalseAndDeletedAtIsNull(100L)).thenReturn(Mono.just(0L));
        when(reactionRepository.existsByPostIdAndAccountId(100L, 1L)).thenReturn(Mono.just(false));

        // Act & Assert
        Mono<PostResponse> result = postService.createPost(1L, 10L, 20L, 30L, request);

        StepVerifier.create(result)
                .expectNextMatches(response ->
                        response.id().equals(100L) &&
                                response.content().equals("Sample test post content") &&
                                response.commentCount() == 0 &&
                                !response.hasReacted()
                )
                .verifyComplete();

        verify(accountRepository, times(1)).findByIdAndDeletedAtIsNull(1L);
        verify(postRepository, times(1)).save(any(Post.class));
    }

    @Test
    void reportPost_ShouldAutoHidePost_WhenThresholdReached() {
        // Arrange
        Long postId = 100L;
        Long reporterId = 2L;
        ao.creativemode.kixi.feed.dto.postReport.PostReportRequest reportRequest =
                new ao.creativemode.kixi.feed.dto.postReport.PostReportRequest("Offensive content");

        when(postRepository.findByIdAndIsHiddenFalseAndDeletedAtIsNull(postId)).thenReturn(Mono.just(mockPost));
        when(reportRepository.existsByPostIdAndReporterAccountId(postId, reporterId)).thenReturn(Mono.just(false));
        when(reportRepository.save(any(PostReport.class))).thenReturn(Mono.just(new PostReport()));

        // Return 5 reports to trigger the auto-hide threshold (AUTO_HIDE_REPORT_THRESHOLD = 5)
        when(reportRepository.countByPostId(postId)).thenReturn(Mono.just(5L));
        when(postRepository.findById(postId)).thenReturn(Mono.just(mockPost));
        when(postRepository.save(any(Post.class))).thenReturn(Mono.just(mockPost));

        // Act & Assert
        StepVerifier.create(postService.reportPost(postId, reporterId, reportRequest))
                .expectNextCount(1)
                .verifyComplete();

        verify(reportRepository, times(1)).save(any(PostReport.class));
        verify(postRepository, times(1)).save(any(Post.class)); // Verifies that hidePost was invoked
    }
}