package ao.creativemode.kixi.dto.questionimage;

import jakarta.validation.constraints.NotNull;

/**
 * DTO for creating or updating QuestionImage metadata.
 * Note: imageUrl is excluded from the request as it is generated by the server during upload.
 */
public record QuestionImageRequest(
        @NotNull(message = "Question ID is required")
        Long questionId,

        String caption,

        Integer orderIndex
) {}