CREATE TABLE subjects (
    code        VARCHAR(50) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    short_name    VARCHAR(100) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE DEFAULT NULL,

    CONSTRAINT uk_subjects_name_code UNIQUE (name, code)
)