-- Kixi schema ownership is handled by Flyway in the backend service.
--
-- PostgreSQL executes files in this directory before the backend starts. Keeping
-- this file intentionally empty prevents Docker init and Flyway from creating
-- competing versions of the schema.
